### PR TITLE
Rmarkdown file by Haoyu Qi.

### PR DESCRIPTION
**Pull request by Jeremy-Dionysos**
1. Using tm package to do words bag. 
2. remove ingredients with too high or too low frequency
3. random forest fun too long.

### CODE REVIEW

**Comment by EricTing** [comment]
Can not reproduce your results by running the r mark down file.

After open the `script.Rmd` and `setwd` to the _data_ directory, `run all` gives the error:

```
cannot rename file '/Users/yunding/.active-rstudio-document.R' to '/Users/yunding/.active-rstudio-document', reason 'No such file or directory'
```

**Comment by Jeremy-Lucid** [comment]
See the .md file directly.

**Comment by EricTing** [comment]
I can reproduce the results now. Please include only the necessary source code in the git repository, such as the _script.Rmd_ and _script.html_

**Comment by EricTing** [comment]
see b38bd61

**Pull request closed without merging**
